<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Http\JsonResponse;
use Illuminate\Support\Str;
use App\Models\Cart;
use Illuminate\Support\Facades\Auth;
use Lunar\Models\CartLine;
use Lunar\Models\Currency;
use Lunar\Models\Channel;
use Lunar\Models\ProductVariant;

class CartController extends Controller
{
    /**
     * Create a new cart or get existing cart.
     * POST /api/cart
     */
    public function store(Request $request): JsonResponse
    {
        // Get or create cart based on cart_id (UUID) in request
        $cartId = $request->input('cart_id');
        
        if ($cartId) {
            $cart = Cart::findByUuid($cartId);
            if ($cart) {
                return $this->formatCartResponse($cart);
            }
        }

        // Create new cart with UUID (auto-generated by model)
        $currency = Currency::getDefault();
        $channel = Channel::getDefault();

        $user = Auth::guard('sanctum')->user();

        $cart = new Cart([
            'currency_id' => $currency->id,
            'channel_id' => $channel->id,
            'user_id' => $user ? $user->id : null,
        ]);
        $cart->save();

        return $this->formatCartResponse($cart, 201);
    }

    /**
     * Get current cart.
     * GET /api/cart
     */
    public function show(Request $request): JsonResponse
    {
        $cartId = $request->input('cart_id');
        
        if (!$cartId) {
            return response()->json(['message' => 'cart_id is required.'], 400);
        }

        $cart = Cart::findByUuid($cartId);

        $this->authenticateCart($cart);

        if (!$cart) {
            return response()->json(['message' => 'Cart not found.'], 404);
        }

        return $this->formatCartResponse($cart);
    }

    /**
     * Add item to cart.
     * POST /api/cart/items
     */
    public function addItem(Request $request): JsonResponse
    {
        $validated = $request->validate([
            'cart_id' => 'required|string',
            'variant_id' => 'required|integer|exists:lunar_product_variants,id',
            'quantity' => 'integer|min:1',
        ]);

        $cart = Cart::findByUuid($validated['cart_id']);
        
        if (!$cart) {
            return response()->json(['message' => 'Cart not found.'], 404);
        }
        $this->authenticateCart($cart);

        $variant = ProductVariant::find($validated['variant_id']);

        if (!$variant) {
            return response()->json(['message' => 'Product variant not found.'], 404);
        }

        // Check if item already exists in cart
        $existingLine = $cart->lines()
            ->where('purchasable_type', ProductVariant::class)
            ->where('purchasable_id', $variant->id)
            ->first();

        if ($existingLine) {
            $existingLine->update([
                'quantity' => $existingLine->quantity + ($validated['quantity'] ?? 1),
            ]);
        } else {
            CartLine::create([
                'cart_id' => $cart->id,
                'purchasable_type' => ProductVariant::class,
                'purchasable_id' => $variant->id,
                'quantity' => $validated['quantity'] ?? 1,
            ]);
        }

        $cart->refresh();
        $cart->calculate();

        return $this->formatCartResponse($cart);
    }

    /**
     * Update cart item quantity.
     * PATCH /api/cart/items/{lineId}
     */
    public function updateItem(Request $request, int $lineId): JsonResponse
    {
        $validated = $request->validate([
            'cart_id' => 'required|string',
            'quantity' => 'required|integer|min:1',
        ]);

        $cart = Cart::findByUuid($validated['cart_id']);
        
        if (!$cart) {
            return response()->json(['message' => 'Cart not found.'], 404);
        }
        $this->authenticateCart($cart);

        $line = CartLine::where('cart_id', $cart->id)->where('id', $lineId)->first();

        if (!$line) {
            return response()->json(['message' => 'Cart item not found.'], 404);
        }

        $line->update(['quantity' => $validated['quantity']]);

        $cart->refresh();
        $cart->calculate();

        return $this->formatCartResponse($cart);
    }

    /**
     * Remove item from cart.
     * DELETE /api/cart/items/{lineId}
     */
    public function removeItem(Request $request, int $lineId): JsonResponse
    {
        $validated = $request->validate([
            'cart_id' => 'required|string',
        ]);

        $cart = Cart::findByUuid($validated['cart_id']);
        
        if (!$cart) {
            return response()->json(['message' => 'Cart not found.'], 404);
        }
        $this->authenticateCart($cart);

        $line = CartLine::where('cart_id', $cart->id)->where('id', $lineId)->first();

        if (!$line) {
            return response()->json(['message' => 'Cart item not found.'], 404);
        }

        $line->delete();

        $cart->refresh();
        $cart->calculate();

        return $this->formatCartResponse($cart);
    }

    /**
     * Clear all items from cart.
     * DELETE /api/cart
     */
    public function clear(Request $request): JsonResponse
    {
        $validated = $request->validate([
            'cart_id' => 'required|string',
        ]);

        $cart = Cart::findByUuid($validated['cart_id']);
        
        if (!$cart) {
            return response()->json(['message' => 'Cart not found.'], 404);
        }
        $this->authenticateCart($cart);
        
        $cart->lines()->delete();

        $cart->refresh();
        $cart->calculate();

        return $this->formatCartResponse($cart);
    }

    /**
     * Format cart response with calculated totals.
     */
    private function formatCartResponse(Cart $cart, int $status = 200): JsonResponse
    {
        $cart->load(['lines.purchasable.product']);
        $cart->calculate();

        $lines = $cart->lines->map(function ($line) {
            $purchasable = $line->purchasable;
            
            return [
                'id' => $line->id,
                'variant_id' => $line->purchasable_id,
                'quantity' => $line->quantity,
                'unit_price' => $line->unitPrice?->formatted ?? null,
                'sub_total' => $line->subTotal?->formatted ?? null,
                'total' => $line->total?->formatted ?? null,
                'product' => [
                    'name' => $purchasable?->product?->translateAttribute('name') ?? 'Unknown',
                    'sku' => $purchasable?->sku ?? null,
                    'thumbnail' => $purchasable?->getThumbnailImage() ?? null,
                ],
            ];
        });

        return response()->json([
            'id' => $cart->getIdentifier(),
            'currency_code' => $cart->currency?->code ?? null,
            'sub_total' => $cart->subTotal?->formatted ?? null,
            'tax_total' => $cart->taxTotal?->formatted ?? null,
            'total' => $cart->total?->formatted ?? null,
            'lines' => $lines,
            'lines_count' => $cart->lines->count(),
        ], $status);
    }
    

    private function authenticateCart(Cart $cart): void
    {
        $user = Auth::guard('sanctum')->user();
        if($user && $cart && !$cart->user_id) {
            $cart->user_id = $user->id;
            $cart->save();
        } else {
            // verify that this cart belongs to the authenticated user
            if($user && $cart && $cart->user_id !== $user->id) {
                abort(403, 'Unauthorized access to cart.');
            }
        }

    }
}
